### PR TITLE
Features/movie details

### PR DESCRIPTION
**Pull request by waltad**
I'm inserting a working movie detail tile. No cast or crew yet. Please review.

### CODE REVIEW

**Review by P-Michalski — CHANGES_REQUESTED** [review]
Hi Tadeusz,
Visually, everything seems to be working fine. Also, your way of doing that task seems to be working but I have some things that I would request to be changed.

1. Console says that you lack a "key" value for React somewhere in your code, and it displays red warning.
2. I would strongly suggest other way of routing through subpages, something like it was in to-do-list project (so basically I would recommend something like for example you have route for movies, which is /movies, so the subpage for a particaular movie should look like /movies/:id,
where :id would be the movie id (please check and refer to to-do-list way of doing it). That way would make things simplier and wouldn't mess up some things, and it would also make it possible to link someone url of certain movie with its id.
3. I think that you have overthought some things, for example I see that you are using localStorage to store the movie's id, but if you do it the way I said (which is to route by movie's id) you could use that exact id by using useParams() and also make some selector in Slice to getMovieById or something like that, you will think of a way of making these things work.
4. I would strongly suggest removing "example[...].json" files after you no longer need them.

I see that you have done some hard work there and it is appreciated, but I truly insist on that you make that routing based on something like it was in to-do-list project :)

**Comment by waltad** [comment]
> Hi Tadeusz, Visually, everything seems to be working fine. Also, your way of doing that task seems to be working but I have some things that I would request to be changed.
> 
> 1. Console says that you lack a "key" value for React somewhere in your code, and it displays red warning.
> 2. I would strongly suggest other way of routing through subpages, something like it was in to-do-list project (so basically I would recommend something like for example you have route for movies, which is /movies, so the subpage for a particaular movie should look like /movies/:id,
>    where :id would be the movie id (please check and refer to to-do-list way of doing it). That way would make things simplier and wouldn't mess up some things, and it would also make it possible to link someone url of certain movie with its id.
> 3. I think that you have overthought some things, for example I see that you are using localStorage to store the movie's id, but if you do it the way I said (which is to route by movie's id) you could use that exact id by using useParams() and also make some selector in Slice to getMovieById or something like that, you will think of a way of making these things work.
> 4. I would strongly suggest removing "example[...].json" files after you no longer need them.
> 
> I see that you have done some hard work there and it is appreciated, but I truly insist on that you make that routing based on something like it was in to-do-list project :)

Hi, Piotrek,
Thank You for suggestions.
I moved the id of for a particular movie to the route. This is actually much easier.
I removed localStorage because it is no longer needed.
I removed example files.
The warning problem (lack a "key" value for React) resolved itself.

**Comment by waltad** [comment]
> Hi Tadeusz, Visually, everything seems to be working fine. Also, your way of doing that task seems to be working but I have some things that I would request to be changed.
> 
> 1. Console says that you lack a "key" value for React somewhere in your code, and it displays red warning.
> 2. I would strongly suggest other way of routing through subpages, something like it was in to-do-list project (so basically I would recommend something like for example you have route for movies, which is /movies, so the subpage for a particaular movie should look like /movies/:id,
>    where :id would be the movie id (please check and refer to to-do-list way of doing it). That way would make things simplier and wouldn't mess up some things, and it would also make it possible to link someone url of certain movie with its id.
> 3. I think that you have overthought some things, for example I see that you are using localStorage to store the movie's id, but if you do it the way I said (which is to route by movie's id) you could use that exact id by using useParams() and also make some selector in Slice to getMovieById or something like that, you will think of a way of making these things work.
> 4. I would strongly suggest removing "example[...].json" files after you no longer need them.
> 
> I see that you have done some hard work there and it is appreciated, but I truly insist on that you make that routing based on something like it was in to-do-list project :)

Hi, Piotrek,
Thank You for suggestions.
I moved the id of for a particular movie to the route. This is actually much easier.
I removed localStorage because it is no longer needed.
I removed example files.
The warning problem (lack a "key" value for React) resolved itself

**Comment by P-Michalski** [comment]
Now it seems a lot better ^-^

**Review by P-Michalski — APPROVED** [review]

**Pull request merged**
